name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-etl:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: taxi_db
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ETL Job
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: taxi_db
          DB_USER: admin
          DB_PASS: admin
        run: |
          python etl_job.py

  build-docker:
    runs-on: ubuntu-latest
    needs: test-etl
    steps:
      - uses: actions/checkout@v4

      - name: Build main Docker image
        run: |
          docker build -f Dockerfile -t main-app:latest .

      - name: Build Streamlit Docker image
        run: |
          docker build -f Dockerfile.streamlit -t streamlit-app:latest .