name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ETL Job
        run: |
          python etl_job.py

  build-docker:
    runs-on: ubuntu-latest
    needs: test-etl
    steps:
      - uses: actions/checkout@v4

      - name: Build main Docker image
        run: |
          docker build -f Dockerfile -t main-app:latest .

      - name: Build Streamlit Docker image
        run: |
          docker build -f Dockerfile.streamlit -t streamlit-app:latest .

# Uncomment below if pushing to a container registry like Azure ACR or DockerHub
#      - name: Log in to registry
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
#          username: ${{ secrets.REGISTRY_USERNAME }}
#          password: ${{ secrets.REGISTRY_PASSWORD }}
#
#      - name: Push images
#        run: |
#          docker tag main-app:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/main-app:latest
#          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/main-app:latest
#
#          docker tag streamlit-app:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/streamlit-app:latest
#          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/streamlit-app:latest